P8015_Hw1_agd2159
================
Zander De Jesus
09-23-2023

## Problem 1: Inline R Code and Using GGplot

Beginning by importing required libraries:

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(moderndive)
```

Importing Weather Sample Dataset from Moderndive and initial summary
statistics:

``` r
data("early_january_weather")
weather_df = early_january_weather
weather_df
```

    ## # A tibble: 358 × 15
    ##    origin  year month   day  hour  temp  dewp humid wind_dir wind_speed
    ##    <chr>  <int> <int> <int> <int> <dbl> <dbl> <dbl>    <dbl>      <dbl>
    ##  1 EWR     2013     1     1     1  39.0  26.1  59.4      270      10.4 
    ##  2 EWR     2013     1     1     2  39.0  27.0  61.6      250       8.06
    ##  3 EWR     2013     1     1     3  39.0  28.0  64.4      240      11.5 
    ##  4 EWR     2013     1     1     4  39.9  28.0  62.2      250      12.7 
    ##  5 EWR     2013     1     1     5  39.0  28.0  64.4      260      12.7 
    ##  6 EWR     2013     1     1     6  37.9  28.0  67.2      240      11.5 
    ##  7 EWR     2013     1     1     7  39.0  28.0  64.4      240      15.0 
    ##  8 EWR     2013     1     1     8  39.9  28.0  62.2      250      10.4 
    ##  9 EWR     2013     1     1     9  39.9  28.0  62.2      260      15.0 
    ## 10 EWR     2013     1     1    10  41    28.0  59.6      260      13.8 
    ## # ℹ 348 more rows
    ## # ℹ 5 more variables: wind_gust <dbl>, precip <dbl>, pressure <dbl>,
    ## #   visib <dbl>, time_hour <dttm>

``` r
#Identified Important Variables in this Tibble after observing using these functions:
#view(weather_df)
summary(weather_df)
```

    ##     origin               year          month        day              hour      
    ##  Length:358         Min.   :2013   Min.   :1   Min.   : 1.000   Min.   : 0.00  
    ##  Class :character   1st Qu.:2013   1st Qu.:1   1st Qu.: 4.000   1st Qu.: 6.00  
    ##  Mode  :character   Median :2013   Median :1   Median : 8.000   Median :11.50  
    ##                     Mean   :2013   Mean   :1   Mean   : 8.039   Mean   :11.53  
    ##                     3rd Qu.:2013   3rd Qu.:1   3rd Qu.:12.000   3rd Qu.:17.75  
    ##                     Max.   :2013   Max.   :1   Max.   :15.000   Max.   :23.00  
    ##                                                                                
    ##       temp            dewp           humid           wind_dir    
    ##  Min.   :24.08   Min.   : 8.96   Min.   : 32.86   Min.   :  0.0  
    ##  1st Qu.:33.98   1st Qu.:19.94   1st Qu.: 51.34   1st Qu.:140.0  
    ##  Median :39.02   Median :26.06   Median : 61.67   Median :240.0  
    ##  Mean   :39.58   Mean   :28.06   Mean   : 65.48   Mean   :208.2  
    ##  3rd Qu.:44.96   3rd Qu.:35.06   3rd Qu.: 78.68   3rd Qu.:290.0  
    ##  Max.   :57.92   Max.   :53.06   Max.   :100.00   Max.   :360.0  
    ##                                                   NA's   :5      
    ##    wind_speed       wind_gust         precip            pressure   
    ##  Min.   : 0.000   Min.   :16.11   Min.   :0.000000   Min.   :1011  
    ##  1st Qu.: 5.754   1st Qu.:19.56   1st Qu.:0.000000   1st Qu.:1018  
    ##  Median : 8.055   Median :21.86   Median :0.000000   Median :1022  
    ##  Mean   : 8.226   Mean   :22.53   Mean   :0.002039   Mean   :1023  
    ##  3rd Qu.:11.508   3rd Qu.:25.32   3rd Qu.:0.000000   3rd Qu.:1027  
    ##  Max.   :24.166   Max.   :31.07   Max.   :0.190000   Max.   :1034  
    ##                   NA's   :308                        NA's   :38    
    ##      visib          time_hour                     
    ##  Min.   : 0.120   Min.   :2013-01-01 01:00:00.00  
    ##  1st Qu.: 9.000   1st Qu.:2013-01-04 19:15:00.00  
    ##  Median :10.000   Median :2013-01-08 12:30:00.00  
    ##  Mean   : 8.515   Mean   :2013-01-08 12:28:09.39  
    ##  3rd Qu.:10.000   3rd Qu.:2013-01-12 05:45:00.00  
    ##  Max.   :10.000   Max.   :2013-01-15 23:00:00.00  
    ## 

``` r
nrow(weather_df) 
```

    ## [1] 358

``` r
ncol(weather_df)
```

    ## [1] 15

``` r
mean(pull(weather_df, "temp"))
```

    ## [1] 39.58212

### Prob. 1 Dataframe Summary

This imported dataset, named **weather_df** in this exercise, is a
tibble dataframe that contains the first 15 days of weather readings
from January 2013. Data points for important weather metrics were
recorded on an hourly basis. When evaluated with nrow and ncol, the
dataframe contains 358 rows and 15 columns.

- Weather Variables Measured in this Dataframe include:
  - **Temperature** in Degrees Fahrenheit. The mean temperature across
    these days was **39.5821229 Degrees**.
  - **Dewpoint**, which had a mean of 28.057095 and standard deviation
    of 10.7260695.
  - **Relative Humidity**, with a mean of 65.4767039 and standard
    deviation of 18.9453049.
  - **Wind Direction** in degrees from true north. Mean 208.2 degrees.
  - **Wind Speed**. Mean of 8.2258269 and standard deviation of
    4.6116356.
  - **Wind Gust**, not measured for most entries. Mean 22.53.
  - **Precipitation**. Mean of 0.0020391 and standard deviation of
    0.0132008.
  - **Atmospheric Pressure** measured in pascals. Mean of 1023 Pa.
  - **Visibility**. Mean of 8.5153352 and 2.9971051.
  - Exact Time Stamps by Hour.

### Prob. 1 Scatterplot Generation

``` r
#Define Variables 
Time_Hour = pull(weather_df, "time_hour")
Temp = pull(weather_df, "temp")
Humidity = pull(weather_df, "humid")

ggplot(weather_df, aes(x= Time_Hour, y = Temp, color = Humidity)) + geom_point()
```

![](p8015_hw1_agd2159_files/figure-gfm/Weather%20Scatterplot-1.png)<!-- -->

``` r
ggsave("ScatterplotFirstDraft.pdf")
```

    ## Saving 7 x 5 in image

The Scatterplot above visualizes the hourly temperature readings
recorded across this 15 day period in January, with each point colored
by its respective humidity readings. The lighter the blue, the higher
the humidity.

From this Scatterplot we can see that there is a visible day-night cycle
visualized, where temperature dips down during the night hours and rises
higher over the next day. Across the week, the temperature appears to
rise from day to day, with January 1 and 2 having average temperatures
between 30 and 40 degrees and the middle of the week around January 7
rising into the 50 degrees. Near the end of the measurement period,
there is the largest temperature increase from January 12-14 where the
temperature rises from the mid 40s into the mid 50s. The Humidity
appears to be highest from January 12 - 14 as well. By January 15, the
temperature drops back down to low 40s high 30 degrees.

# Problem 2: Generating Random Dataframe and Manipulating Variables

``` r
set.seed(1234)

prob2_df = 
  tibble(
    num_sample = rnorm(10),
    log_vec = num_sample > 0,
    char_vec = c("A", "B", "C", "D", "E", "AA", "BB", "CC", "DD", "EE"),
    factor_vec = factor(c("lemon", "lemon", "lemon", "mango","mango","mango","mango","apple", "apple", "apple"))
  )

prob2_df
```

    ## # A tibble: 10 × 4
    ##    num_sample log_vec char_vec factor_vec
    ##         <dbl> <lgl>   <chr>    <fct>     
    ##  1     -1.21  FALSE   A        lemon     
    ##  2      0.277 TRUE    B        lemon     
    ##  3      1.08  TRUE    C        lemon     
    ##  4     -2.35  FALSE   D        mango     
    ##  5      0.429 TRUE    E        mango     
    ##  6      0.506 TRUE    AA       mango     
    ##  7     -0.575 FALSE   BB       mango     
    ##  8     -0.547 FALSE   CC       apple     
    ##  9     -0.564 FALSE   DD       apple     
    ## 10     -0.890 FALSE   EE       apple
